Repository dipakkr/A-to-Z-Resources-for-Students, pull requests merged in 2018-11, with the labels that each got.

#997 Add a react native course
  README.md
Labels: change-requested

#713 Flutter Resources added
  Android.md
Labels: hacktoberfest, update-requested

#868 added link for R resource
  README.md
Labels: approved, conflict-found

#896 Added Resource in 'Additional links' section
  README.md
Labels: approved

#909 Igorlmgx branch
  CONTRIBUTORS.md
Labels: approved, conflict-found

#911 add J Bowler plus 2 courses
  CONTRIBUTORS.md
  README.md
Labels: approved, conflict-found

#918 added Giordi Fungula to list
  CONTRIBUTORS.md
Labels: approved, conflict-found

#919 Added Spanish Translation
  CONTRIBUTORS.md
  translation/README-es-latam.md
Labels: approved

#942 Added Invision App
  CONTRIBUTORS.md
  README.md
Labels: review requested, under review

#953 Added Blog link to GSOC.md
  GSOC.md
Labels: approved

#1031 Update table of contents
  README.md
Labels: change-requested

#1054 Added the Links for the Machine learning and Python
  CONTRIBUTORS.md
  README.md
Labels: approved

#1048 Update README.md
  README.md
Labels: update-requested

#1067 Added a new course on C++, the one that's up on Udacity
  CONTRIBUTORS.md
  README.md
Labels: approved
