Repository dipakkr/A-to-Z-Resources-for-Students, pull requests merged in 2018-10, with the labels that each got.

#41 Add /frontenddevtools/packagemanagers
  README.md
Labels: enhancement

#42 Add/frontenddevtools/bundlers
  README.md
Labels: enhancement

#46 Added School of AI course
  Blockchain.md
Labels: hacktoberfest

#59 Added YHack
  README.md
Labels: hacktoberfest

#60 Added HackNY Fellows Program
  README.md
Labels: hacktoberfest

#67 AlgoDS in different programming languages
  README.md
Labels: hacktoberfest

#102 Add Android Development Resources
  Android.md
Labels: enhancement, hacktoberfest

#107 Added a full stack project in projects.md
  projects.md
Labels: hacktoberfest, help wanted

#177 Add new backend recs
  README.md
  new-contributors.md
Labels: hacktoberfest

#175 Corrected typo errors
  README.md
Labels: hacktoberfest

#174 #150 Add Translation in your Language
  README-pt-br.md
  new-contributors.md
  projects.md
Labels: hacktoberfest

#667 Add
  ML.md
Labels: hacktoberfest

#655 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, update-requested

#660 Add "PHP: The Right Way" to PHP resources
  CONTRIBUTORS.md
  README.md
Labels: hacktoberfest

#664 Add Umme Ammara to Contributors list
  CONTRIBUTORS.md
Labels: update-requested

#659 Add Nerdzão Brazil to "Developer Clubs and Meetups"
  CONTRIBUTORS.md
  README.md
Labels: hacktoberfest, update-requested

#666 #604 README.md clean up and formatting
  CONTRIBUTORS.md
  README.md
Labels: hacktoberfest, under review

#750 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: update-requested

#704 Fixed typo, added resources
  README.md
Labels: approved

#706 Added 1.10 Geeks For Geeks
  README.md
Labels: approved

#709 add multiple regression
  Machine_cleansheet.md
  README.md
Labels: approved

#710 Add Ingressive Campus ambassadorship program
  README.md
Labels: approved

#711 Developers Conference Mauritius By MSCC
  README.md
  translation/README-de-DE.md
Labels: approved

#791 Replaced Azure for Students with Imagine pack
  README.md
Labels: under review

#743 Added a cheat sheet for Flexbox
  README.md
Labels: approved

#744 grammer corrected
  DataStructuresCheetSheet.md
Labels: approved

#746 adding myself as a contributor
  CONTRIBUTORS.md
Labels: approved

#736 added first commit
  CONTRIBUTORS.md
Labels: approved

#732 add link to upcase learning resource for ruby and post-boot camp deve…
  README.md
Labels: approved, hacktoberfest

#720 Blockchain and Bitcoin
  Blockchain.md
Labels: approved, hacktoberfest

#869 Updated DS & Algo Topic with Tutorials
  CONTRIBUTORS.md
  README.md
Labels: approved

#640 Add JS functional programming resource to README
  README.md
Labels: approved, hacktoberfest

#656 Added Chainhero tutorial
  Blockchain.md
  CONTRIBUTORS.md
Labels: hacktoberfest, update-requested

#873 fix wrong link for Microsoft Student Partner
  README.md
Labels: approved

#762 Update README.md
  README.md
Labels: approved, hacktoberfest

#763 Update README.md
  README.md
Labels: approved, hacktoberfest

#770 docs: Add LearnGitBranching resource
  README.md
Labels: approved, hacktoberfest

#771 docs: Add Learning JavaScript Design Patterns resource
  README.md
Labels: approved, hacktoberfest

#775 added a hash table problem from hackerearth
  DataStructuresCheetSheet.md
Labels: approved

#776 updated amazon ml docs
  ML.md
Labels: approved

#799 Added my name to contribution list :)
  CONTRIBUTORS.md
Labels: approved, conflict-found

#811 Add my name in contributor
  CONTRIBUTORS.md
Labels: approved, conflict-found

#816 Added Node.js handbook and CSS Flexbox resources
  README.md
Labels: review requested

#827 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: invalid, update-requested

#819 updated readme with the list of courses by wes bos
  README.md
Labels: update-requested

#859 my first commit
  CONTRIBUTORS.md
Labels: approved

#861 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: approved

#864 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: approved

#866 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: approved

#671 sckit learn course
  README.md
Labels: update-requested

#729 Add some Hyperledger Composer resources
  Blockchain.md
  CONTRIBUTORS.md
Labels: approved, hacktoberfest

#740 first commit
  CONTRIBUTORS.md
Labels: change-requested

#748 Fix links on table of contents, #462
  README.md
Labels: under review

#808 #755: Fixed the format of content in BlockChain.md
  Blockchain.md
Labels: approved, conflict-found

#749 fixed link in the table of contents
  README.md
Labels: duplicate, under review

#790 fixed issue #757 and made the file look interactive
  DataStructuresCheetSheet.md
Labels: conflict-found, review requested

#797 More fixes to TOC
  README.md
Labels: conflict-found, under review

#847 added Python and machine learning courses
  Android.md
  CONTRIBUTORS.md
  README.md
Labels: review requested

#850 Add backend and frontend roadmaps
  README.md
Labels: review requested

#872 added example.js to resources
  README.md
Labels: approved

#876 Update README.md
  CONTRIBUTORS.md
  README.md
Labels: approved

#882 Typo Angualr => Angular in README.md
  README.md
Labels: approved

#892 Fixed markdown for links
  README.md
Labels: under review

#897 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: approved, conflict-found

#898 Add hello world
  CONTRIBUTORS.md
Labels: approved, conflict-found

#899 Added Name to CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: approved, conflict-found

#902 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
  DataStructuresCheetSheet.md
Labels: approved, change-requested

#904 Added myself to contributors and added an event
  CONTRIBUTORS.md
  README.md
Labels: approved, conflict-found

#644 Adding new topic (Preparing interview books (technical)) #636
  CONTRIBUTORS.md
  README.md
Labels: conflict-found, hacktoberfest

#836 Update hackathons with dates
  README.md
Labels: approved, conflict-found

#986 added name to contributors
  CONTRIBUTORS.md
Labels: approved, hacktoberfest

#801 Add resource for deep learning
  ML.md
Labels: under review

#877 Added machine learning course link
  CONTRIBUTORS.md
  README.md
Labels: conflict-found, review requested

#1006 Add name to CONTRUBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest

#947 Add programming notes for professionals repo
  CONTRIBUTORS.md
  README.md
Labels: under review
